name: build the app
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pull repository
        uses: actions/checkout@v2
      - name: Print current direcory
        run: pwd
      - name: Prient files in there
        run: ls
      - name: Check dotnet
        run: dotnet
      - name: Check npm
        run: npm